[package]
name = "serve"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
indoc = "1.0.7"
poem = { version = "1.3.50", features = ["static-files"] }
tokio = { version = "1.23.0", features = ["rt-multi-thread"] }
