[package]
name = "serve"
version = "0.6.2"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
indoc = "1.0.7"
poem = { version = "1.3.50", features = ["static-files"] }
thiserror = "1.0.44"
tokio = { version = "1.23.0", features = ["rt-multi-thread", "process"] }
